select count(*) from (
    select BUSINESS_ID, NAME, STARS, REVIEW_COUNT, IS_OPEN 
    from BUSINESS 
    WHERE BUSINESS_ID IS NOT NULL
    OR NAME IS NOT NULL
    OR STARS IS NOT NULL
    OR REVIEW_COUNT IS NOT NULL
    OR IS_OPEN IS NOT NULL
  group by BUSINESS_ID, NAME, STARS, REVIEW_COUNT, IS_OPEN
  );

select count(*) from (
    select REVIEW_ID, BUSINESS_ID,USER_ID,'DATE', STARS, USEFUL, COOL
    from FACT_REVIEW
    WHERE REVIEW_ID IS NOT NULL
    OR BUSINESS_ID IS NOT NULL
    OR USER_ID IS NOT NULL
    OR 'DATE' IS NOT NULL
    OR STARS IS NOT NULL
    OR COOL IS NOT NULL
  group by REVIEW_ID, BUSINESS_ID,USER_ID,'DATE', STARS, USEFUL, COOL
    );


select count(*) from (
    select bu.BUSINESS_ID, re.BUSINESS_ID, re.REVIEW_ID
    FROM BUSINESS bu RIGHT OUTER JOIN FACT_REVIEW re
    ON bu.BUSINESS_ID = re.BUSINESS_ID
);


select bu.BUSINESS_ID, re.REVIEW_ID FROM BUSINESS bu, FACT_REVIEW re WHERE bu.BUSINESS_ID = re.BUSINESS_ID AND bu.BUSINESS_ID = 'lcarrupLCJ-a9LGkTUtMIw';